name: Upload ndpolator to pypi on release

on:
    workflow_dispatch:
    pull_request:
    release:
        types: [created]

jobs:
    build-sdist:
        name: Package source distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Build sdist tarball
              run: |
                pipx run build --sdist
            - uses: actions/upload-artifact@v5
              with:
                name: cibw-sdist
                path: dist/*.tar.gz

    build-wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: ${{ github.event_name == 'pull_request' && fromJSON('["ubuntu-latest"]') || fromJSON('["ubuntu-24.04", "macos-14", "macos-15"]') }}
        steps:
            - name: Checkout the sources
              uses: actions/checkout@v5
            - name: Build wheels
              uses: pypa/cibuildwheel@v3.2.0
              env:
                CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-* cp313-*"
                CIBW_SKIP: "*-win32 *-manylinux_i686"
            - uses: actions/upload-artifact@v5
              with:
                name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
                path: ./wheelhouse/*.whl

    publish-to-pypi:
        if: github.event_name != 'pull_request'
        needs: [build-sdist, build-wheels]
        name: Publish release to PyPI
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/ndpolator
        permissions:
            id-token: write
        steps:
            - name: Gather sdist tarball and wheels
              uses: actions/download-artifact@v5
              with:
                pattern: cibw-*
                path: dist
                merge-multiple: true
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
