name: Upload ndpolator to pypi on release

on:
    workflow_dispatch:
    release:
        types: [created]

jobs:
    build-sdist:
        name: Package source distribution
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build sdist tarball
              run: |
                pipx run build --sdist
            - uses: actions/upload-artifact@v4
              with:
                name: cibw-sdist
                path: dist/*.tar.gz

    build-wheels:
        name: Build wheels on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-24.04, macos-13, macos-14]
        steps:
            - name: Set up python environment
              uses: actions/setup-python@v5
            - name: Checkout the sources
              uses: actions/checkout@v4
            - name: Install cibuildwheel
              run: |
                pip install --upgrade pip
                pip install cubuildwheel==2.18.1
            - name: Build wheels
              run: |
                python -m cibuildwheel --output-dir wheelhouse
            - uses: actions/upload-artifact@v4
              with:
                name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
                path: ./wheelhouse/*.whl

    publish-to-pypi:
        needs: [build-sdist, build-wheels]
        name: Publish release to PyPI
        runs-on: ubuntu-latest
        environment:
            name: pypi
            url: https://pypi.org/p/ndpolator
        permissions:
            id-token: write
        steps:
            - name: Gather sdist tarball and wheels
              uses: actions/download-artifact@v4
              with:
                pattern: cibw-*
                path: dist
                merge-multiple: true
            - name: Publish package distributions to PyPI
              uses: pypa/gh-action-pypi-publish@release/v1
